### ISSUE TITLE
[Patch] Building with `--with-python` fails with "plugin_python.c:(.text+0x58): undefined reference to `PyString_FromString'".

### ISSUE THREAD

**Issue by dreirund** [TangoCash/lcd4linux#5]
In order to build with `--with-python` with python3.13, [this patch](https://github.com/Hierosoft/lcd4linux/pull/15.patch) is needed, otherwise it fails with  
```
plugin_python.c:(.text+0x58): undefined reference to `PyString_FromString'
```

while linkint.

Regards!
